### ISSUE TITLE
Can I install pyserial in 3d slicer?

### ISSUE THREAD

**Issue by timeanddoctor** [tokjun/ELTemplate#2]
Dear Pro. tokjun

I am a neurosurgery and I went to use pyserial with 3D slicer. Can I pip it in slicer?

Thanks.

**Comment by tokjun** [comment]
Hi @timeanddoctor,

The latest version of 3D Slicer should work with pip.

https://www.slicer.org/wiki/Documentation/Labs/Pip

Thanks!

**Comment by timeanddoctor** [comment]
Thank you very much!
